/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

export const bool = true;

export const false = false;

/* ultimate question of life, the universe, and everything */
export const int = 42;

/* This is
a multiline
description */
export const str = "hello world!";

export const unquoted = float;

